export const types = {
  // AUTH ACTIONS
  REGISTER_USER_START: 'REGISTER_USER_START',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
  // PRODUCT ACTIONS
  GET_INDIVIDUAL_PRODUCT_START: 'GET_INDIVIDUAL_PRODUCT_START',
  GET_INDIVIDUAL_PRODUCT_SUCCESS: 'GET_INDIVIDUAL_PRODUCT_SUCCESS',
  GET_INDIVIDUAL_PRODUCT_FAIL: 'GET_INDIVIDUAL_PRODUCT_FAIL',
  GET_PRODUCTS_START: 'GET_PRODUCTS_START',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL',
  ADD_PRODUCTS_START: 'ADD_PRODUCTS_START',
  ADD_PRODUCTS_SUCCESS: 'ADD_PRODUCTS_SUCCESS',
  ADD_PRODUCTS_FAIL: 'ADD_PRODUCTS_FAIL',
  EDIT_PRODUCTS_START: 'EDIT_PRODUCTS_START',
  EDIT_PRODUCTS_SUCCESS: 'EDIT_PRODUCTS_SUCCESS',
  EDIT_PRODUCTS_FAIL: 'EDIT_PRODUCTS_FAIL',
  // CART ACTIONS
  GET_CART_START: 'GET_CART_START',
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  GET_CART_FAIL: 'GET_CART_FAIL',
  ADD_CART_START: 'ADD_CART_START',
  ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
  ADD_CART_FAIL: 'ADD_CART_FAIL',
}
